    
sudo: false
language: cpp
compiler:
  - g++
os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - g++-8

script:
  - cd LinuxServer/
  - g++ main.cpp -o LinuxServer
  - cd ../
  - bash startTesting.sh
